name: hadolint

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

permissions:
  contents: read

jobs:
  hadolint:
    name: hadolint
    uses: book000/templates/.github/workflows/reusable-hadolint-ci.yml@76e83535fd3f9ddc99c9333efb8a4f7dd886edd1 # master
